export * from "./TecnologiasInformacion/CatalogosTIColumns"
export * from "./TecnologiasInformacion/CatalogosTIForm"
export * from "./TecnologiasInformacion/CatalogosTIRow"
export * from "./TecnologiasInformacion/CatalogosTIService"
export * from "./TecnologiasInformacion/CategoriaTIColumns"
export * from "./TecnologiasInformacion/CategoriaTIForm"
export * from "./TecnologiasInformacion/CategoriaTIRow"
export * from "./TecnologiasInformacion/CategoriaTIService"